// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/game-ui/DeepSpace.tsx": () => import("../components/mockups/game-ui/DeepSpace.tsx"),
  "./components/mockups/game-ui/NeonArcade.tsx": () => import("../components/mockups/game-ui/NeonArcade.tsx")
};
